### ISSUE TITLE
Low FPS results in missing/skipping inputs

### ISSUE THREAD

**Issue by robohunterx** [Santi871/DCSWaypointEditor#13]
Not necessarily an issue with your coding, but my potato computer, when getting pretty bad FPS in MP (We're talking like 15) can run so slow that the DCS BIOS commands are coming in too quickly for the screens to keep up. This resulted in the program missing the first button press to go to the Waypoint Data page in the F-18. I noticed sometimes it would make it to that screen, but then the PRECISE mode click wasn't registered.

Adding the ability to decrease the input speed of the program might work to alleviate this issue on my potato. Even if it's slower, it's still 20x faster than me typing them in by hand. 👍

**Comment by Santi871** [comment]
9937aa643bdad654ee7d0bf5e732b2f8f32c62a1
