### ISSUE TITLE
current build tests positive for trojan

### ISSUE THREAD

**Issue by derammo** [Santi871/DCSWaypointEditor#27]
trojan detected by microsoft built-in anti virus

your build https://github.com/Santi871/DCSWaypointEditor/releases/tag/v0.9.9b1

triggered anti virus on main exe after unzip (did not run it)

![image](https://user-images.githubusercontent.com/817160/65822086-9479b580-e20c-11e9-8be9-e7cb3b823e22.png)

**Comment by Santi871** [comment]
Should be fixed with latest version.

**Comment by derammo** [comment]
the current version 0.9.9b2 no longer reports as a trojan, but it only executed successfully once.  On the second attempt to run it, Windows Defender said it contained a "virus or unwanted software" and quarantined it   I could compile it from source I guess?

**Comment by derammo** [comment]
specifically, it complains about Behavior:Win32/CredentialAccess.Q!ml
